#include <glad/gl.h>

/* ── Function pointer definitions ──────────────────────────────────────── */
PFNGLCLEARCOLORPROC              glad_glClearColor              = NULL;
PFNGLCLEARPROC                   glad_glClear                   = NULL;
PFNGLENABLEPROC                  glad_glEnable                  = NULL;
PFNGLDISABLEPROC                 glad_glDisable                 = NULL;
PFNGLDEPTHFUNCPROC               glad_glDepthFunc               = NULL;
PFNGLVIEWPORTPROC                glad_glViewport                = NULL;
PFNGLGETERRORPROC                glad_glGetError                = NULL;
PFNGLGETINTEGERVPROC             glad_glGetIntegerv             = NULL;
PFNGLLINEWIDTHPROC               glad_glLineWidth               = NULL;
PFNGLDRAWARRAYSPROC              glad_glDrawArrays              = NULL;
PFNGLBLENDFUNCPROC               glad_glBlendFunc               = NULL;
PFNGLGENTEXTURESPROC             glad_glGenTextures             = NULL;
PFNGLDELETETEXTURESPROC          glad_glDeleteTextures          = NULL;
PFNGLBINDTEXTUREPROC             glad_glBindTexture             = NULL;
PFNGLTEXIMAGE2DPROC              glad_glTexImage2D              = NULL;
PFNGLCOMPRESSEDTEXIMAGE2DPROC   glad_glCompressedTexImage2D    = NULL;
PFNGLTEXPARAMETERIPROC           glad_glTexParameteri           = NULL;
PFNGLACTIVETEXTUREPROC           glad_glActiveTexture           = NULL;
PFNGLGENBUFFERSPROC              glad_glGenBuffers              = NULL;
PFNGLDELETEBUFFERSPROC           glad_glDeleteBuffers           = NULL;
PFNGLBINDBUFFERPROC              glad_glBindBuffer              = NULL;
PFNGLBUFFERDATAPROC              glad_glBufferData              = NULL;
PFNGLGENVERTEXARRAYSPROC         glad_glGenVertexArrays         = NULL;
PFNGLDELETEVERTEXARRAYSPROC      glad_glDeleteVertexArrays      = NULL;
PFNGLBINDVERTEXARRAYPROC         glad_glBindVertexArray         = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glad_glEnableVertexAttribArray = NULL;
PFNGLVERTEXATTRIBPOINTERPROC     glad_glVertexAttribPointer     = NULL;
PFNGLVERTEXATTRIBIPOINTERPROC    glad_glVertexAttribIPointer    = NULL;
PFNGLDRAWELEMENTSPROC            glad_glDrawElements            = NULL;
PFNGLPOLYGONMODEPROC             glad_glPolygonMode             = NULL;
PFNGLBINDBUFFERBASEPROC          glad_glBindBufferBase          = NULL;
PFNGLCREATESHADERPROC            glad_glCreateShader            = NULL;
PFNGLDELETESHADERPROC            glad_glDeleteShader            = NULL;
PFNGLSHADERSOURCEPROC            glad_glShaderSource            = NULL;
PFNGLCOMPILESHADERPROC           glad_glCompileShader           = NULL;
PFNGLGETSHADERIVPROC             glad_glGetShaderiv             = NULL;
PFNGLGETSHADERINFOLOGPROC        glad_glGetShaderInfoLog        = NULL;
PFNGLCREATEPROGRAMPROC           glad_glCreateProgram           = NULL;
PFNGLDELETEPROGRAMPROC           glad_glDeleteProgram           = NULL;
PFNGLATTACHSHADERPROC            glad_glAttachShader            = NULL;
PFNGLLINKPROGRAMPROC             glad_glLinkProgram             = NULL;
PFNGLUSEPROGRAMPROC              glad_glUseProgram              = NULL;
PFNGLGETPROGRAMIVPROC            glad_glGetProgramiv            = NULL;
PFNGLGETPROGRAMINFOLOGPROC       glad_glGetProgramInfoLog       = NULL;
PFNGLGETUNIFORMLOCATIONPROC      glad_glGetUniformLocation      = NULL;
PFNGLUNIFORM1IPROC               glad_glUniform1i               = NULL;
PFNGLUNIFORM1FPROC               glad_glUniform1f               = NULL;
PFNGLUNIFORM1IVPROC              glad_glUniform1iv              = NULL;
PFNGLUNIFORM1FVPROC              glad_glUniform1fv              = NULL;
PFNGLUNIFORM4FPROC               glad_glUniform4f               = NULL;
PFNGLUNIFORM4FVPROC              glad_glUniform4fv              = NULL;
PFNGLUNIFORM3FVPROC              glad_glUniform3fv              = NULL;
PFNGLUNIFORMMATRIX4FVPROC        glad_glUniformMatrix4fv        = NULL;
PFNGLDEPTHMASKPROC               glad_glDepthMask               = NULL;
PFNGLISENABLED                   glad_glIsEnabled               = NULL;
PFNGLGENFRAMEBUFFERSPROC         glad_glGenFramebuffers         = NULL;
PFNGLDELETEFRAMEBUFFERSPROC      glad_glDeleteFramebuffers      = NULL;
PFNGLBINDFRAMEBUFFERPROC         glad_glBindFramebuffer         = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC    glad_glFramebufferTexture2D    = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glad_glFramebufferRenderbuffer = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC  glad_glCheckFramebufferStatus  = NULL;
PFNGLGENRENDERBUFFERSPROC        glad_glGenRenderbuffers        = NULL;
PFNGLDELETERENDERBUFFERSPROC     glad_glDeleteRenderbuffers     = NULL;
PFNGLBINDRENDERBUFFERPROC        glad_glBindRenderbuffer        = NULL;
PFNGLRENDERBUFFERSTORAGEPROC     glad_glRenderbufferStorage     = NULL;

/* ── Loader ──────────────────────────────────────────────────────────────── */
#define LOAD(type, name) glad_##name = (type)load(#name)

int gladLoadGL(GLADloadfunc load) {
    LOAD(PFNGLCLEARCOLORPROC,              glClearColor);
    LOAD(PFNGLCLEARPROC,                   glClear);
    LOAD(PFNGLENABLEPROC,                  glEnable);
    LOAD(PFNGLDISABLEPROC,                 glDisable);
    LOAD(PFNGLDEPTHFUNCPROC,               glDepthFunc);
    LOAD(PFNGLVIEWPORTPROC,                glViewport);
    LOAD(PFNGLGETERRORPROC,                glGetError);
    LOAD(PFNGLGETINTEGERVPROC,             glGetIntegerv);
    LOAD(PFNGLLINEWIDTHPROC,               glLineWidth);
    LOAD(PFNGLDRAWARRAYSPROC,              glDrawArrays);
    LOAD(PFNGLBLENDFUNCPROC,               glBlendFunc);
    LOAD(PFNGLGENTEXTURESPROC,             glGenTextures);
    LOAD(PFNGLDELETETEXTURESPROC,          glDeleteTextures);
    LOAD(PFNGLBINDTEXTUREPROC,             glBindTexture);
    LOAD(PFNGLTEXIMAGE2DPROC,              glTexImage2D);
    LOAD(PFNGLCOMPRESSEDTEXIMAGE2DPROC,   glCompressedTexImage2D);
    LOAD(PFNGLTEXPARAMETERIPROC,           glTexParameteri);
    LOAD(PFNGLACTIVETEXTUREPROC,           glActiveTexture);
    LOAD(PFNGLGENBUFFERSPROC,              glGenBuffers);
    LOAD(PFNGLDELETEBUFFERSPROC,           glDeleteBuffers);
    LOAD(PFNGLBINDBUFFERPROC,              glBindBuffer);
    LOAD(PFNGLBUFFERDATAPROC,              glBufferData);
    LOAD(PFNGLGENVERTEXARRAYSPROC,         glGenVertexArrays);
    LOAD(PFNGLDELETEVERTEXARRAYSPROC,      glDeleteVertexArrays);
    LOAD(PFNGLBINDVERTEXARRAYPROC,         glBindVertexArray);
    LOAD(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
    LOAD(PFNGLVERTEXATTRIBPOINTERPROC,     glVertexAttribPointer);
    LOAD(PFNGLVERTEXATTRIBIPOINTERPROC,    glVertexAttribIPointer);
    LOAD(PFNGLDRAWELEMENTSPROC,            glDrawElements);
    LOAD(PFNGLPOLYGONMODEPROC,             glPolygonMode);
    LOAD(PFNGLBINDBUFFERBASEPROC,          glBindBufferBase);
    LOAD(PFNGLCREATESHADERPROC,            glCreateShader);
    LOAD(PFNGLDELETESHADERPROC,            glDeleteShader);
    LOAD(PFNGLSHADERSOURCEPROC,            glShaderSource);
    LOAD(PFNGLCOMPILESHADERPROC,           glCompileShader);
    LOAD(PFNGLGETSHADERIVPROC,             glGetShaderiv);
    LOAD(PFNGLGETSHADERINFOLOGPROC,        glGetShaderInfoLog);
    LOAD(PFNGLCREATEPROGRAMPROC,           glCreateProgram);
    LOAD(PFNGLDELETEPROGRAMPROC,           glDeleteProgram);
    LOAD(PFNGLATTACHSHADERPROC,            glAttachShader);
    LOAD(PFNGLLINKPROGRAMPROC,             glLinkProgram);
    LOAD(PFNGLUSEPROGRAMPROC,              glUseProgram);
    LOAD(PFNGLGETPROGRAMIVPROC,            glGetProgramiv);
    LOAD(PFNGLGETPROGRAMINFOLOGPROC,       glGetProgramInfoLog);
    LOAD(PFNGLGETUNIFORMLOCATIONPROC,      glGetUniformLocation);
    LOAD(PFNGLUNIFORM1IPROC,               glUniform1i);
    LOAD(PFNGLUNIFORM1FPROC,               glUniform1f);
    LOAD(PFNGLUNIFORM1IVPROC,              glUniform1iv);
    LOAD(PFNGLUNIFORM1FVPROC,              glUniform1fv);
    LOAD(PFNGLUNIFORM4FPROC,               glUniform4f);
    LOAD(PFNGLUNIFORM4FVPROC,              glUniform4fv);
    LOAD(PFNGLUNIFORM3FVPROC,              glUniform3fv);
    LOAD(PFNGLUNIFORMMATRIX4FVPROC,        glUniformMatrix4fv);
    LOAD(PFNGLDEPTHMASKPROC,               glDepthMask);
    LOAD(PFNGLISENABLED,                   glIsEnabled);
    LOAD(PFNGLGENFRAMEBUFFERSPROC,         glGenFramebuffers);
    LOAD(PFNGLDELETEFRAMEBUFFERSPROC,      glDeleteFramebuffers);
    LOAD(PFNGLBINDFRAMEBUFFERPROC,         glBindFramebuffer);
    LOAD(PFNGLFRAMEBUFFERTEXTURE2DPROC,    glFramebufferTexture2D);
    LOAD(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer);
    LOAD(PFNGLCHECKFRAMEBUFFERSTATUSPROC,  glCheckFramebufferStatus);
    LOAD(PFNGLGENRENDERBUFFERSPROC,        glGenRenderbuffers);
    LOAD(PFNGLDELETERENDERBUFFERSPROC,     glDeleteRenderbuffers);
    LOAD(PFNGLBINDRENDERBUFFERPROC,        glBindRenderbuffer);
    LOAD(PFNGLRENDERBUFFERSTORAGEPROC,     glRenderbufferStorage);

    return glad_glCreateProgram != NULL;
}
